spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234
    # type: com.mchange.v2.c3p0.ComboPooledDataSource
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      exclude: static/**,application.yml
      enabled: false
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
